### ISSUE TITLE
$20 | Short bio UI issue

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#10]
![image](https://user-images.githubusercontent.com/42398485/59124174-9ef20580-8924-11e9-8f28-cd0bc7ae4a19.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon

**Actual:** Short bio UI issue

**Expected:** Short Bio should display on a single line

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please check PR #8 feedback

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues PR updated

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Thanks, you getting any error when run `npm run build`?
What version of nodejs you're using?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji What's your TopCoder handle?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues Pkdurlabhji
