### ISSUE TITLE
$50 | Topcoder main page is displayed after logging in

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/navigation-component#102]
**Reproduction steps:**
prereq.: the user is logged out

1. Open the test URL
2. Click LOGIN at the top right corner
3. Enter the credentials and proceed
4. Observe

**Expected result:** 
The user stays on the challenges page after logging in

**Actual result:** 
The user is redirected to topcoder home page after logging in

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: iPad (5th generation)

OS: iOS 12.2

Browser: Safari

**Comment by SathyaJayabal** [comment]
Verified in Test env. Please see the attached video.
[login.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4089690/login.mov.zip)

**Comment by macs054** [comment]
Verified in Beta
[issue_102_beta.zip](https://github.com/topcoder-platform/navigation-component/files/4259584/issue_102_beta.zip)

**Comment by SathyaJayabal** [comment]
verified in prod
[login.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4265137/login.mov.zip)
