### ISSUE TITLE
$30 | New Nav: Regarding clicking on Topcoder Logo

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#104]
For V2, the logo should direct them to "my Dashboard" if they're logged in. and www.topcoder.com if they are logged out

**Comment by luizrrodrigues** [comment]
@nahidshahin Please check feedback here: https://github.com/topcoder-platform/navigation-component/pull/92#pullrequestreview-342464132

**Comment by luizrrodrigues** [comment]
@nahidshahin any status in this one?

**Comment by luizrrodrigues** [comment]
@nahidshahin We opening this one to pickup, please reassign if you able to complete the fix.

Thanks.

**Comment by nithyaasworld** [comment]
Verified in Test env.

**Comment by macs054** [comment]
Verified in Beta
[issue_104_beta.zip](https://github.com/topcoder-platform/navigation-component/files/4259604/issue_104_beta.zip)

**Comment by SathyaJayabal** [comment]
verified in prod
[logo.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4265148/logo.mov.zip)
