### ISSUE TITLE
$15 | All Sub menus> Sub-menu has an item after the menu name 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#11]
![image](https://user-images.githubusercontent.com/42398485/59124052-4d497b00-8924-11e9-8f48-a7059363951b.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Work > Tracks

**Actual:** Sub-menu should not display that extra item

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@nahidshahin Please check feedback in PR #5

**Comment by nahidshahin** [comment]
@luizrrodrigues this task involves added Icon + place icons appropriately. The prize seems little bit small.

**Comment by luizrrodrigues** [comment]
I think is okay, second requirement is just add `padding-left: 5px`

**Comment by luizrrodrigues** [comment]
@nahidshahin Please check feedback here: https://github.com/topcoder-platform/navigation-component/pull/5#pullrequestreview-250206706

**Comment by luizrrodrigues** [comment]
@nahidshahin I do a double check in real device, wrong icon still showing in Android.

Check:
![image](https://user-images.githubusercontent.com/7029641/59733988-204f6f00-9226-11e9-8bda-d3eda5884dbb.png)

**Comment by luizrrodrigues** [comment]
@nahidshahin Please give me some status on this or if we can Open For Pickup

**Comment by r0hit-gupta** [comment]
@luizrrodrigues I would like to pick this up. Thanks.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Cool, thanks.

**Comment by r0hit-gupta** [comment]
@luizrrodrigues unable to reproduce. Can you please test again in Chrome's incognito mode? The cache might be a problem.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Note, this happen only in Android device

**Comment by r0hit-gupta** [comment]
Yes. It looks fine to me on OnePlus 6 - Android 8.1.0. Please try again once in incognito and if its still an issue, will look deeper into it.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Yeah, looks like was problem with caching.

Thanks for checking.

**Comment by nahidshahin** [comment]
@luizrrodrigues sorry I was in travel. Just being curious, who has get paid?

**Comment by luizrrodrigues** [comment]
Hey @nahidshahin, payment already, check:
https://www.topcoder.com/challenges/30094080/?type=develop&noncache=true&tab=details
