### ISSUE TITLE
$20 | Hover state is not displayed

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/navigation-component#12]
**Reproduction Steps**
1. Open the test URL and log in 
2. Click on Work 
3. Click on Compete 
4. Hover over Competitive programming
5. Click on Tracks
6. Hover over the opened menu items

**Expected results**
When the user hovers over a menu items, the hover over state is displayed

**Actual results**
When the user hovers over a menu items, the hover over state is not displayed

**Screenshot**
![screenshot1](https://user-images.githubusercontent.com/45698232/59123749-deaff180-8912-11e9-9063-92c8f5339a49.png)

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
	Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please send a fix in next 12h, or this will be open for pickup.

Thanks.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues can u please try now
PR
https://github.com/topcoder-platform/navigation-component

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji I'm still seeing issue in Safari, but not hover mark in left side.

Please let me know what `node` version you're using.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues i dont think it related to node version.

node version: 10.13.0

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Any status to fix Safari bug?

**Comment by ya3ya6** [comment]
@PrakashDurlabhji May i suggest using [https://www.lambdatest.com/](url) for testing in safari? it has inspector as well, so you can test your css in realtime even (instead of making your localhost available over internet)

**Comment by PrakashDurlabhji** [comment]
@ya3ya6 thanks a lot, will immediately check on it once my other task is completed.

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Any status on this one?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues trying it as i do not wish to lose my efforts

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Thanks

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Can open this one to pickup?

**Comment by r0hit-gupta** [comment]
@luizrrodrigues may I pick this one up? I already have a fix for safari. Thanks.

**Comment by PrakashDurlabhji** [comment]
some time else i will open

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues can you please try now,

https://github.com/topcoder-platform/navigation-component/pull/4

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Checking

@r0hit-gupta Hold please, checking latest PR from @PrakashDurlabhji

**Comment by r0hit-gupta** [comment]
@luizrrodrigues sure. The new PR still doesn't work on Safari for me.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues i feel got the solution, updating it

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues please try now once

**Comment by r0hit-gupta** [comment]
@luizrrodrigues please let me know when I can pick this up. The latest PR still doesn't work for me.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues it is done, your suggestions are committed.

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please run `nom run build` always when make some changes to update and commit `/dist` folder.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues kindly be online, will resolve it nowitself. we shall close this now, just need your some help of testing

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Now I able to see changes, but looks like not working.

You can't test in Safari?

@r0hit-gupta You PR will be a new one or a fix to @PrakashDurlabhji PR?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues found solution and working one, which wil work in safari for sure. One final time testing please.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues please test now

**Comment by luizrrodrigues** [comment]
I'll back in 10min to test 
Please check other issue assigned to you, thanks.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues sure

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues working?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Yep, just making a double check. :)

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues done?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Looks good now, thanks for all effort on this. :)

@r0hit-gupta thanks for check this

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues sorry for being too late but i saw in my list that payment for this is pending, even though it is marked as paid here, but this ticket is not paid, whereas other tickets which are marked paid are actually paid, but not this one. can you confirm once again?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues apology for confusion, this ticket is paid but with different title in pacts.

 "navigation-component#12"
this is title used.

whereas I was searching for "hover state is not displayed#12"

thanks kindly ignore previous comment

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji  No problem, sorry for the confusion :)
