### ISSUE TITLE
$15 | dark mode displayed in mobile web but light mode on desktop

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/navigation-component#126]
**Reproduction steps:**

1. Open the test URL on desktop and log in
2. Click on 'Work' > 'Community'
3. Observe the mode (whether light or dark) of the second level menu
4. Open the test URL in mobile web and log in
5. Open the hamburger menu > 'Work' > 'Community'
6. Repeat step 3

**Expected result:** 
If the light mode is shown on desktop, the light mode is displayed on mobile web too

**Actual result:** 
The light mode is displayed on desktop while dark mode on mobile web

**Frequency:** 5/5

**Device/Browser/OS:** 

Device#1: Laptop

OS#1: Windows 10 pro 64-bit

Browser/s#1:
Chrome 75.0.3770.80
Firefox 67.0.1
Microsoft Edge 44.17763.1.0
IE 11.503.17763.0

Device#2: Axon ZTE A20170

OS#2: Android 7.1.1

Browser/s#2:
Chrome 74.0.3729.157

**Sceenshot of actual results in mobile web:**
![p4VZIQXNy0M](https://user-images.githubusercontent.com/45698232/59154946-a99ac080-8a32-11e9-8678-77635dd6bd58.jpg)

**Sceenshot of actual results on desktop:**
![lightmode](https://user-images.githubusercontent.com/45698232/59154950-bc14fa00-8a32-11e9-9079-63f31f2d65b4.png)

**Light vs dark mode for mobile web as shown on marvel app:**
![lightvsdark](https://user-images.githubusercontent.com/45698232/59154961-f088b600-8a32-11e9-98c2-b445344c3d18.JPG)

**Light vs dark mode for desktop as shown on marvel app:**
![lightvsdark1](https://user-images.githubusercontent.com/45698232/59154966-faaab480-8a32-11e9-9600-73744b0bd97a.JPG)

**Comment by SathyaJayabal** [comment]
Verified in test env. 
<img width="494" alt="Screenshot 2020-01-21 at 11 48 13 AM" src="https://user-images.githubusercontent.com/58783823/72780141-0f476000-3c44-11ea-8e8f-0c2032bbd056.png">

**Comment by macs054** [comment]
Verified in Beta
![87863611_1559138320906831_7233477971669942272_n](https://user-images.githubusercontent.com/1199534/75415394-74d6ec80-5966-11ea-8cfa-5bd3f4555f02.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="523" alt="Screenshot 2020-02-28 at 9 02 41 AM" src="https://user-images.githubusercontent.com/58783823/75508137-27f82200-5a09-11ea-9d5e-605f84126809.png">
