### ISSUE TITLE
$40 | New Nav - Mobile View UI Issues

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/navigation-component#13]
Original Spec : https://marvelapp.com/1dgiejg6/screen/54473669

1. Logo not in the center

![not-in-the center](https://user-images.githubusercontent.com/683231/58796325-9cd53180-861a-11e9-974a-e1709be7ccb8.png)

2. Horizontal divider not aligned with text, also there is no `X` button to close the popup

![Screenshot_20190603-160049](https://user-images.githubusercontent.com/683231/58796495-0b19f400-861b-11e9-81e3-5206b8af2f6d.png)

**Smartphone **
 - Device: MI A2
 - OS: Android 9
 - Chrome

**Comment by luizrrodrigues** [comment]
@rashmi73 Please check feedback in PR #2

**Comment by rashmi73** [comment]
@luizrrodrigues updated

**Comment by luizrrodrigues** [comment]
@rashmi73 

Logo: Looks good

Profile menu: Items need be aligned with green line.
Check: 
![image](https://user-images.githubusercontent.com/7029641/59466462-ca349300-8e03-11e9-8c70-6248eac3454e.png)

**Comment by rashmi73** [comment]
@luizrrodrigues confuse how much is to be aligned? can you please notify with green markers how it is to be made on above screenshot?

**Comment by luizrrodrigues** [comment]
@rashmi73 Need consistent alignment with **Work** menu:
https://marvelapp.com/89423f8/screen/54595272/handoff

![image](https://user-images.githubusercontent.com/7029641/59467571-65c70300-8e06-11e9-82ae-b8e0b02cae94.png)

**Comment by rashmi73** [comment]
@luizrrodrigues you mean to say

1. "My Dashboard" text is not in same line logo?

2. so left of logo and "My Dashboard" should have equal space to the left?

**Comment by luizrrodrigues** [comment]
@rashmi73 check image bellow, this was shared before. What is not aligned is the dividers, text have right alignment. 

![](https://user-images.githubusercontent.com/683231/58796495-0b19f400-861b-11e9-81e3-5206b8af2f6d.png)


What I see in your submission: 
![image](https://user-images.githubusercontent.com/7029641/59468073-93f91280-8e07-11e9-8291-d9de31788217.png)

**Comment by rashmi73** [comment]
@luizrrodrigues need like this?

https://marvelapp.com/89423f8/screen/55812232

**Comment by luizrrodrigues** [comment]
@rashmi73 Yes.

**Comment by rashmi73** [comment]
@luizrrodrigues updating

**Comment by rashmi73** [comment]
@luizrrodrigues updated 
PR #2

**Comment by rashmi73** [comment]
@luizrrodrigues can you please review this?

**Comment by luizrrodrigues** [comment]
@rashmi73 posting feedback shortly

**Comment by rashmi73** [comment]
@luizrrodrigues PR updated 
PR #2

**Comment by rashmi73** [comment]
@luizrrodrigues PR updated
PR #2

**Comment by rashmi73** [comment]
@luizrrodrigues PR updated
PR #2

**Comment by luizrrodrigues** [comment]
@rashmi73 Thanks
