### ISSUE TITLE
$20 | More drop down is still open when we access the work menu again

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#134]
https://www.screencast.com/t/F0fyNsBSrqC

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work > More
4. Tap on the topcoder logo will go to the main page (Challenges)
5. Tap Menu > Work

**Actual:** More drop down is still open when we access the work menu again

**Expected:** More menu options should be collapsed

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch

**Browser:** Chrome 75.0.3770.80

**Comment by SathyaJayabal** [comment]
Verified in  test env. See attached video
[more.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4089354/more.mov.zip)

**Comment by macs054** [comment]
Verified in Beta
[issue_134_beta.zip](https://github.com/topcoder-platform/navigation-component/files/4259685/issue_134_beta.zip)

**Comment by SathyaJayabal** [comment]
verified in prod
[more.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4265176/more.mov.zip)
