### ISSUE TITLE
$15 | Drop down More menu appears at 175% zoom while Community appears at 200%

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/navigation-component#135]
**Reproduction steps:**

1. Open the test URL and log in
2. Click on 'Work' > Community
3. Zoom in 175% 
4. Observe the menu items in the header
5. Zoom in 200% 
6. Observe the items in the header

**Expected result:** 
Community menu item appears at 175% because there is enough space in the header for it. Or More drop down menu appears at both 175% and 200%

**Actual result:** 
Drop down More menu appears at 175% with only one item - Community, even though there is enough space in the header for it even without the drop down More menu. Community menu item appears at 200% even though the drop down More menu appears at 175%

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Screen resolution:** 1600 x 900
![screenshot1](https://user-images.githubusercontent.com/45698232/59140630-38391000-8955-11e9-82b3-4807d80c2625.png)
![screenshot2](https://user-images.githubusercontent.com/45698232/59140631-38391000-8955-11e9-9efb-a1eaef0d6b8d.png)

**Comment by SathyaJayabal** [comment]
Verified in test env. See attached video

[nav zoom.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4089089/nav.zoom.mov.zip)

**Comment by macs054** [comment]
Verified in Beta. But it varies by screen size, at 1080p the 'More' menu does not appear in 200% and at 250% the menu turns into mobile menu. In lower screen size the 'More' menu does appear.

200%  
![image](https://user-images.githubusercontent.com/1199534/75416615-b1581780-5969-11ea-99b1-8e1e024102af.png)
250%  
![image](https://user-images.githubusercontent.com/1199534/75416681-f5e3b300-5969-11ea-90d2-9bb7ed84452b.png)

Lower screen size
![image](https://user-images.githubusercontent.com/1199534/75416735-1f9cda00-596a-11ea-96f0-9bc9584b70d8.png)

**Comment by SathyaJayabal** [comment]
verified in prod

<img width="1436" alt="Screenshot 2020-02-28 at 9 14 36 AM" src="https://user-images.githubusercontent.com/58783823/75508663-e49eb300-5a0a-11ea-8f75-827dbe6f9378.png">
<img width="1432" alt="Screenshot 2020-02-28 at 9 14 57 AM" src="https://user-images.githubusercontent.com/58783823/75508665-e9fbfd80-5a0a-11ea-8ab4-f0916e791063.png">
