### ISSUE TITLE
$15 | Clicking on the menu separator will open the menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#136]
![image](https://user-images.githubusercontent.com/42398485/59149216-5e53c400-89d8-11e9-8030-17410390b171.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click on menu separator

**Actual:** Clicking on the menu separator will open the menu

**Expected:** Clicking on the menu separator should not open the menu

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Chrome 75.0.3770.80 (Official Build) (64-bit) | Microsoft Edge 44.17763.1.0 | IE11 | Firefox

**Reproducibility Rate:** 3/3

**Comment by luizrrodrigues** [comment]
@iversonLv Still able to click in | in menu, check:

[Screen Recording 2020-01-20 at 11.09.40.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4086542/Screen.Recording.2020-01-20.at.11.09.40.mov.zip)

**Comment by iversonLv** [comment]
@luizrrodrigues Please check the update.
Ready for review
Thanks.

**Comment by nithyaasworld** [comment]
Verified in test env.

**Comment by macs054** [comment]
Verified in Beta
[issue_136_beta.zip](https://github.com/topcoder-platform/navigation-component/files/4259740/issue_136_beta.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[div.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4265190/div.mov.zip)
