### ISSUE TITLE
More Menu -> Duplicate menu options added

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#141]
1. click on more > in the tablet view. Make sure the window size is such that "compete" "tracks" and "explore " are all under the more menu.
2. select either "tracks" or "explore" under more
3. the selected menu appears on the main nav
4. More menu now has two "compete" menu options
<img width="787" alt="Screenshot 2020-01-21 at 2 52 00 PM" src="https://user-images.githubusercontent.com/58783823/72791859-0e232c80-3c5e-11ea-9298-4a5980699714.png">
<img width="795" alt="Screenshot 2020-01-21 at 2 52 14 PM" src="https://user-images.githubusercontent.com/58783823/72791862-0e232c80-3c5e-11ea-9d75-1b3d088a51bd.png">

5. When compete is selected after this it is moved to the second place in the more menu
<img width="791" alt="Screenshot 2020-01-21 at 2 52 57 PM" src="https://user-images.githubusercontent.com/58783823/72791881-154a3a80-3c5e-11ea-8583-79251b8570ea.png">

**Comment by SathyaJayabal** [comment]
The wrong sub menu item is highlighted in this case
<img width="870" alt="Screenshot 2020-01-21 at 3 58 04 PM" src="https://user-images.githubusercontent.com/58783823/72797730-a96ccf80-3c67-11ea-839b-976c53add7d9.png">
<img width="800" alt="Screenshot 2020-01-21 at 3 59 32 PM" src="https://user-images.githubusercontent.com/58783823/72797732-a96ccf80-3c67-11ea-988c-0127d5dfb059.png">

**Comment by luizrrodrigues** [comment]
Duplicate of #101

**Comment by SathyaJayabal** [comment]
Closing this as this is tracked in #101
