### ISSUE TITLE
$20 | New nav - hide white secondary menus when empty 

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/navigation-component#142]
If some of:
- https://github.com/topcoder-platform/community-app/blob/25b95419ac4f14f36c186d6a7e04312e565a5ce4/config/default.js#L323
- https://github.com/topcoder-platform/community-app/blob/25b95419ac4f14f36c186d6a7e04312e565a5ce4/config/default.js#L308

is empty do not show the corresponding menu element/area.

**Comment by luizrrodrigues** [comment]
@gets0ul Need hide secondary menu and arrow from mobile too:

![image](https://user-images.githubusercontent.com/7029641/72851651-ef875a80-3c8a-11ea-89c4-c5486a7c9fec.png)

**Comment by gets0ul** [comment]
@luizrrodrigues PR updated for mobile menu

**Comment by luizrrodrigues** [comment]
@gets0ul still see some issues with your approach, like still seeing arrow and in menu when submenu not exist. But based in your approach I have fixed other issues, please take a look: https://github.com/topcoder-platform/navigation-component/pull/146/files

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @kkartunov How can we reproduce / test this issue ?

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I'll add video verification here.

**Comment by gets0ul** [comment]
@luizrrodrigues Why is it not getting into 'Paid' status?  
  
@SathyaJayabal To test you need to set the submenu to be empty https://github.com/topcoder-platform/navigation-component/issues/142#issuecomment-572643345

**Comment by luizrrodrigues** [comment]
@gets0ul Sorry delay here, I'll provide a video to QA team pass this one.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Please check videos below:
https://drive.google.com/open?id=1crnhjLtmSXWLoy_MgD55x7ck4J96NKX3
https://drive.google.com/open?id=1EcLpgarPo9hX8FoDk32eKMPKUoUeljmP

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , thank you for the videos.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , please confirm that this cannot be verified on beta.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yes, the verification need be via local env, like shared in the video.

**Comment by SathyaJayabal** [comment]
Cannot be verified in production.
