### ISSUE TITLE
Notifications - Space between bell icon and pink mark

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#158]
**Describe the bug**
1. The space between the notification icon and the pink dot seems more than the design
2. The hover state background circle is not centered.

**Expected behavior**
Need match with the design
![](https://user-images.githubusercontent.com/58783823/74900757-c3184880-53c6-11ea-895d-5a63aa969717.png)

**Screenshots**
1. ![](https://user-images.githubusercontent.com/58783823/74900693-a54ae380-53c6-11ea-9944-8b766dadb425.png)

2. ![](https://user-images.githubusercontent.com/58783823/74900802-ddeabd00-53c6-11ea-84fc-12d010d0b1c5.png)

**Comment by SathyaJayabal** [comment]
Verified in test env
<img width="86" alt="Screenshot 2020-03-03 at 9 14 20 AM" src="https://user-images.githubusercontent.com/58783823/75741099-8f76e000-5d2f-11ea-9e24-bf78b71511b6.png">
<img width="44" alt="Screenshot 2020-03-03 at 9 14 56 AM" src="https://user-images.githubusercontent.com/58783823/75741101-9140a380-5d2f-11ea-93fa-84ec8895c784.png">

**Comment by SathyaJayabal** [comment]
verified on beta(feature branch)
<img width="52" alt="Screenshot 2020-03-26 at 6 47 54 PM" src="https://user-images.githubusercontent.com/58783823/77651135-5c241b80-6f92-11ea-85bf-4efd27e2a166.png">
<img width="1440" alt="Screenshot 2020-03-26 at 6 26 43 PM" src="https://user-images.githubusercontent.com/58783823/77651174-67774700-6f92-11ea-9ac5-1384a56b5a02.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="43" alt="Screenshot 2020-03-30 at 2 55 17 PM" src="https://user-images.githubusercontent.com/58783823/77897877-e40e6c00-7297-11ea-8457-6a6ba1222850.png">

**Comment by codejamtc** [comment]
The space between the notification icon and the pink dot seems more than the design

![image](https://user-images.githubusercontent.com/42398485/77913280-996dff00-7259-11ea-8d61-88594d23fa09.png)


The hover state background circle is not centered.

![image](https://user-images.githubusercontent.com/42398485/77913266-92df8780-7259-11ea-8060-f0113ad3f71f.png)
![image](https://user-images.githubusercontent.com/42398485/77913333-ac80cf00-7259-11ea-8c53-a177e2608199.png)
