### ISSUE TITLE
Notifications - The title is not aligned correctly in mobile view

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#159]
**Describe the bug**
The notifications title is not aligned correctly in mobile view

**Expected behavior**
The notifications title need to be centered in mobile view

**Screenshots**
![](https://user-images.githubusercontent.com/58783823/74900856-0c689800-53c7-11ea-96b0-c6dc17cc7137.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - Browser: Safari

**Comment by SathyaJayabal** [comment]
verified on test
<img width="501" alt="Screenshot 2020-03-03 at 9 26 44 AM" src="https://user-images.githubusercontent.com/58783823/75741750-9141a300-5d31-11ea-9874-c16faebe06a8.png">

**Comment by SathyaJayabal** [comment]
verified on beta (feature branch)
<img width="548" alt="Screenshot 2020-03-26 at 5 33 59 PM" src="https://user-images.githubusercontent.com/58783823/77645024-0ba7c080-6f88-11ea-919d-7c6ccbc6990f.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="502" alt="Screenshot 2020-03-30 at 1 46 07 PM" src="https://user-images.githubusercontent.com/58783823/77893241-4b74ed80-7291-11ea-81ef-52c7d2e8265a.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="498" alt="Screenshot 2020-03-30 at 6 13 04 PM" src="https://user-images.githubusercontent.com/58783823/77913702-5ab86300-72b2-11ea-9326-39ebbdfb3193.png">
