### ISSUE TITLE
$10 | Username cut off from the top

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#16]
![image](https://user-images.githubusercontent.com/42398485/59130269-96a1c680-8934-11e9-8727-b18d59c5fab8.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Profile

**Actual:** Username cut off from the top

**Expected:** Should have some spacing from the above

**Reproducibility Rate:** 3/3

**Environment:** iPhone 5S, iOS 12.2

**Browser:** Safari 12

**Comment by rashmi73** [comment]
@luizrrodrigues kindly check updated 
https://github.com/topcoder-platform/navigation-component/pull/15

**Comment by rashmi73** [comment]
@luizrrodrigues can you please review this?

**Comment by luizrrodrigues** [comment]
@rashmi73 Looks good, thanks.

**Comment by luizrrodrigues** [comment]
@rashmi73 What is your TopCoder handle?

**Comment by rashmi73** [comment]
@luizrrodrigues rashmi73
