### ISSUE TITLE
Notifications - Make "Mark All as Read" disabled if all notifications already read

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#160]
**Describe the bug**
When all notifications already read, the "Mark All as Read" link still active

**To Reproduce**
1. Go to the Notification Panel
2. Click on Mark All as Read
3. Note the link still active

**Expected behavior**
"Mark All as Read" need be disabled state if all notifications already read

**Comment by SathyaJayabal** [comment]
verified on test
<img width="477" alt="Screenshot 2020-03-03 at 9 26 30 AM" src="https://user-images.githubusercontent.com/58783823/75741612-242e0d80-5d31-11ea-9d3c-dcd1b1984243.png">
<img width="501" alt="Screenshot 2020-03-03 at 9 26 44 AM" src="https://user-images.githubusercontent.com/58783823/75741616-255f3a80-5d31-11ea-89a6-e386b09ccd6e.png">

**Comment by SathyaJayabal** [comment]
verified on beta(feature branch)
<img width="508" alt="Screenshot 2020-03-26 at 6 53 27 PM" src="https://user-images.githubusercontent.com/58783823/77651736-3cd9be00-6f93-11ea-8fd0-ad749cf90879.png">
![Uploading Screenshot 2020-03-26 at 6.53.45 PM.png…]()

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="502" alt="Screenshot 2020-03-30 at 1 46 07 PM" src="https://user-images.githubusercontent.com/58783823/77893406-8119d680-7291-11ea-9b79-59927d918d15.png">
<img width="1440" alt="Screenshot 2020-03-30 at 1 55 57 PM" src="https://user-images.githubusercontent.com/58783823/77893412-82e39a00-7291-11ea-9bee-e40c3ff401b0.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="498" alt="Screenshot 2020-03-30 at 6 13 04 PM" src="https://user-images.githubusercontent.com/58783823/77913777-7e7ba900-72b2-11ea-987f-da10c33bb082.png">
<img width="1440" alt="Screenshot 2020-03-30 at 5 53 01 PM" src="https://user-images.githubusercontent.com/58783823/77913782-820f3000-72b2-11ea-857b-7095e48bdb0b.png">
