### ISSUE TITLE
Notifications - Unseen notifications counter in mobile view

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#161]
**Describe the bug**
Currently, unseen notifications counter showing all messages and in red color.

**Expected behavior**
Counter needs to show only the total of unseen notifications.
If no unseen notifications:
- Remove counter;
- Change bell color to black (like Notification text)

**Screenshots**
![](https://user-images.githubusercontent.com/47536078/74955999-4da67b00-53ba-11ea-9aa3-d0fb95a670f8.png)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , the notification icon is in grey instead of black.

<img width="639" alt="Screenshot 2020-03-03 at 9 22 28 AM" src="https://user-images.githubusercontent.com/58783823/75741442-93efc880-5d30-11ea-9899-03dd3e72fa07.png">

**Comment by Oanh-and-only-Oanh** [comment]
Thanks @SathyaJayabal. 
Going to mark as Pass as this is very minor UI.

**Comment by SathyaJayabal** [comment]
verified on beta(feature branch)
seen
<img width="499" alt="Screenshot 2020-03-26 at 6 46 12 PM" src="https://user-images.githubusercontent.com/58783823/77651436-cccb3800-6f92-11ea-9d2a-ebf049f81b1e.png">
unseen
<img width="501" alt="Screenshot 2020-03-26 at 6 27 26 PM" src="https://user-images.githubusercontent.com/58783823/77651466-d9e82700-6f92-11ea-8808-a9f288f7c8c5.png">

**Comment by SathyaJayabal** [comment]
verified on beta (develop)
<img width="532" alt="Screenshot 2020-03-30 at 2 20 49 PM" src="https://user-images.githubusercontent.com/58783823/77893549-b1617500-7291-11ea-9bd7-cf2c837fc114.png">

**Comment by SathyaJayabal** [comment]
<img width="505" alt="Screenshot 2020-03-30 at 6 21 52 PM" src="https://user-images.githubusercontent.com/58783823/77914306-5a6c9780-72b3-11ea-87f4-ed0e764d24e1.png">

**Comment by codejamtc** [comment]
**Unseen**

![Pixel XL_ScreenShot_20200330](https://user-images.githubusercontent.com/42398485/77914464-9542e100-725b-11ea-9362-d06e7fca4db1.jpg)

**Seen**

![Pixel XL_ScreenShot_20200330_1](https://user-images.githubusercontent.com/42398485/77914423-84926b00-725b-11ea-9841-ae208edda48b.jpg)
