### ISSUE TITLE
Notifications - Remove the completed challenges section from the popup

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#162]
Remove the completed challenges section from the popup.

So Notifications Popup will show:
- Active Challenges 
- Broadcast

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This one is ready for QA

**Comment by SathyaJayabal** [comment]
verified on test

**Comment by SathyaJayabal** [comment]
Verified on beta (feature  branch)
<img width="1440" alt="Screenshot 2020-03-26 at 6 26 43 PM" src="https://user-images.githubusercontent.com/58783823/77651373-b2915a00-6f92-11ea-9721-7fb66eafc8ef.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="1440" alt="Screenshot 2020-03-30 at 2 18 35 PM" src="https://user-images.githubusercontent.com/58783823/77893604-c0482780-7291-11ea-956b-31d2a5d75481.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-30 at 5 53 01 PM" src="https://user-images.githubusercontent.com/58783823/77913361-bcc49880-72b1-11ea-8c7f-edd5bdee771b.png">
