### ISSUE TITLE
Notifications - Opening the notifications bar does not make the red dot disappear

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/navigation-component#163]
When clicking the bell icon the red dot should disappear when the notifications bar is opened.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , This happens when a new broadcast notification is shown.
[notif.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4316570/notif.mov.zip)

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This one was fixed.

note: The red dot will disappear when closing the popup window or if on the listing page when navigating to a new page.

**Comment by SathyaJayabal** [comment]
verified on test
[Archive.zip](https://github.com/topcoder-platform/navigation-component/files/4348441/Archive.zip)

**Comment by SathyaJayabal** [comment]
verified on beta(feature branch)

**Comment by codejamtc** [comment]
I was able to reproduce only one here;

**1. The red dot will disappear when closing the popup window**
2. If on the listing page when navigating to a new page.

https://www.screencast.com/t/5wMAbeVznwA8
