### ISSUE TITLE
Update nav to reflect thrive links for tracks pages

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#168]
Update nav to reflect thrive links for tracks pages

Find details here
https://github.com/topcoder-platform/community-app/issues/4125#issuecomment-606428767

**Comment by Jobee1** [comment]
When the user is not logged in, they are not pointing to the "Tracks" in the header instead it is pointing to "Community".

Attached video and screenshot for reference.

![Screenshot_42](https://user-images.githubusercontent.com/48575864/78224455-507faa00-74e8-11ea-930d-7538b179b2d9.png)


[issue.zip](https://github.com/topcoder-platform/navigation-component/files/4419590/issue.zip)

**Comment by sandhiyakavi** [comment]
Tested in Test Environment.Working as expected.

[#168_before_login.zip](https://github.com/topcoder-platform/navigation-component/files/4459734/168_before_login.zip)
[#168_after_login.zip](https://github.com/topcoder-platform/navigation-component/files/4459735/168_after_login.zip)

**Comment by SathyaJayabal** [comment]
closed by #4260
