### ISSUE TITLE
Ability to navigate back to THRIVE homepage from an article

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/navigation-component#170]
**Current problem:**
Currently the way our 2nd level navigation works, you cannot re-click the page that you are on
so when someone is on an article in Thrive and they want to go to the Thrive homepage people try clicking on it and its disabled

**Expect behavior:**
If user is on a THRIVE article 
URL https://www.topcoder.com/thrive/articles/  enable the ability to click THRIVE on secondary navigation to go to the THRIVE homepage URL https://www.topcoder.com/thrive

**Comment by sandhiyakavi** [comment]
Tested.Working as expected.

[#170.zip](https://github.com/topcoder-platform/navigation-component/files/4459787/170.zip)

**Comment by SathyaJayabal** [comment]
closed by #4261
