### ISSUE TITLE
Navi should NOT do full reload on pages

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/navigation-component#175]
- Navi should use `<Link>` instead of `<a>` for menu items to avoid full reload for relative links and utilize the React router.
- For absolute links, it should be doing a full reload.

**Comment by luizrrodrigues** [comment]
@kkartunov PR:
https://github.com/topcoder-platform/navigation-component/pull/176

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, are you waiting for review by @sushil?

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Need to run QA before merge with `develop`

**Comment by kkartunov** [comment]
@luizrrodrigues it somehow has broken the "More" toggler for large menus.
![image](https://user-images.githubusercontent.com/5585002/84438215-d33a8900-ac3e-11ea-876c-d39a4762e9c4.png)

**Comment by kkartunov** [comment]
@luizrrodrigues there is another bug I just found. See https://drive.google.com/file/d/1LrFeeqNSFcAGLlFou91BUw8GC0nOJKVO/view

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , how do we verify this one?

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @kkartunov , there seems to be alignment issues in the more menu

<img width="791" alt="Screenshot 2020-06-22 at 4 39 11 PM" src="https://user-images.githubusercontent.com/58783823/85282268-169bbf80-b4a9-11ea-817b-c3cfbea2228e.png">
<img width="832" alt="Screenshot 2020-06-22 at 4 39 18 PM" src="https://user-images.githubusercontent.com/58783823/85282282-1bf90a00-b4a9-11ea-9f62-569720ff54a8.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This one needs to check on page with second level menu with relative links, like TCO page.

Alignment issue, I'll fix this shortly and push a hotfix.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I think this already fixed. Can you confirm please?

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , navigation does not reload relative links. Will track the alignment issue on more menu in a separate issue
