### ISSUE TITLE
Add support for custom link on navi menu logo

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/navigation-component#177]
Scope: As per title

Example1: on https://community-app.topcoder.com/__community__/tco21 clicking on the logo should be navigating users to the TCO21 home page instead of `/my-dashboard`

Example2: on https://tco20.topcoder.com (test with logged user) clicking on the logo should be navigating users to the TCO20 home page instead of `/my-dashboard`

**Comment by SathyaJayabal** [comment]
@kkartunov 

tco21 site (https://community-app.topcoder-dev.com/__community__/tco21)
Logged in user - Redirects to TCO21 home as expected
Logged out user - Redirects to TCO21 home as expected

TC Community Site (https://community-app.topcoder-dev.com/challenges)
Logged in user - redirects to my Dashboard - as expected
Logged out user - redirects to topcoder homepage, as expected

tco20 site (https://community-app.topcoder-dev.com/__community__/tco20/) 
Does not work as expected 
Logged in user - redirects to topcoder homepage, must redirect to tco20 home
Logged out user - redirects to topcoder homepage, must redirect to tco20 home

[logo_custom link.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4823647/logo_custom.link.mov.zip)

**Comment by kkartunov** [comment]
@SathyaJayabal thanks.
For tco20 site (https://community-app.topcoder-dev.com/__community__/tco20/) please try now. It was not configured from Contentful side. I fixed it

**Comment by SathyaJayabal** [comment]
@kkartunov , tco20 site is good now. Tco19 site is also good.
[tco20.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4823724/tco20.mov.zip)

**Comment by kkartunov** [comment]
@SathyaJayabal good to close this one now. Thanks.
