### ISSUE TITLE
$30 | Top part of the page is hidden by the sub menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#18]
![image](https://user-images.githubusercontent.com/42398485/59125553-46bd0280-8928-11e9-860a-202e819fb87e.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Work > Compete

**Actual:** Top part of the page is hidden by the sub menu

**Expected:** Should display the content below the sub menu

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9 (Mobile and Tabs)

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Thanks
