### ISSUE TITLE
$30 | Below page position is also changing when scrolling through the profile menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#30]
![image](https://user-images.githubusercontent.com/42398485/59127294-e5e3f900-892c-11e9-960b-2a97eeda8550.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Tracks
4. Click Menu > Profile > scroll the items
5. Click close
6. Check the page position

**Actual:** Below page position is also changing when scrolling through the profile menu

**Expected:** Should not scroll the page

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@r0hit-gupta What is your TC handle?

**Comment by r0hit-gupta** [comment]
@luizrrodrigues my TC handle is https://www.topcoder.com/members/rohitgupta_

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Incluse underscore, right?
rohitgupta_

**Comment by r0hit-gupta** [comment]
@luizrrodrigues yes.
