### ISSUE TITLE
$115 | New Nav - Need be always expanded when you navigate between pages.

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/navigation-component#35]
**Describe the bug**

"Challenges" navigation not working from the dashboard

**To Reproduce**

1. Go to `https://test-community-app.topcoder-dev.com/challenges`
2. The content area needs more margin. 
3. Compare it with 
https://test-community-app.topcoder-dev.com/settings/profile
https://test-community-app.topcoder-dev.com/my-dashboard

**Expected behavior**

The respective target page should be loaded.

**Screenshots**

![Topcoder Challenges 2019-06-03 13-39-30](https://user-images.githubusercontent.com/683231/58786578-7f499d00-8605-11e9-89ba-0f5fda6a80b4.png)

**Desktop:**
 - OS: Mac
 - Chrome

**Comment by luizrrodrigues** [comment]
@ya3ya6 Cool, looks good.

Request approve about raise the prize from $20 to $40.

**Comment by ya3ya6** [comment]
@luizrrodrigues Thanks.

**Comment by luizrrodrigues** [comment]
Thanks guys
@sexta13 $75
@ya3ya6 $40
