### ISSUE TITLE
Default menu for the pages that doesnt exists in menu

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#41]
There are some pages that doesn't exist in the Navigation menu. 

Examples:
1. Any member profile page other than the own profile Ex: /members/TonyJ being logged in as mess
2. Challenge details page
3. User menu --> Settings

Expected Behaviour: When such pages are accessed, we should just show the Community menu expanded with no selection indicator.

**Comment by nithyaasworld** [comment]
@luizrrodrigues At 25th second, can you please remove the selection indicator that is present under the Community?  

If the page is not in the menu items, lets not show any selection indicator for any of the menu items.

Thanks.

**Comment by luizrrodrigues** [comment]
@nithyaasworld You sure about that?
We showing *Dashboard*, *My Profile* and *Payments* in secondary menu, so I think *Community* need be selected.
Please confirm

**Comment by nithyaasworld** [comment]
Yes @luizrrodrigues 

At 25th second of the video, you are in User menu -> Settings page. This screen is not part of the community menu (Dashboard or My Profile or Payments). 

So its more appropriate if we do not display any selection indicator for such pages which are not present in the menus.

**Comment by luizrrodrigues** [comment]
@nithyaasworld So need remove indicator and secondary menu too, right?

**Comment by nithyaasworld** [comment]
Yes, right @luizrrodrigues

**Comment by nithyaasworld** [comment]
Thanks @luizrrodrigues 

But the selection indicator is not shown if I click on any other first level menus being in one of the screens that doesn't exist in menu.

![image](https://user-images.githubusercontent.com/5114190/60940882-b3963480-a2fa-11e9-844f-ad434b22348f.png)

**Comment by luizrrodrigues** [comment]
@nithyaasworld  I think we can close this one.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues I dont see the fix. The selection indicators are still not shown for some pages. 
While they appear for some pages.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Okay, I see now. 
We talking about arrow indicator.

**Comment by lakshmiathreya** [comment]
cc @lakshmiathreya @nithyaasworld

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I thing we can pass this one, because the another issue reported here will follow up here: https://github.com/topcoder-platform/navigation-component/issues/62

Right?

**Comment by SathyaJayabal** [comment]
Ok, I will add this example too #62

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1438" alt="Screenshot 2019-12-19 at 8 28 26 PM" src="https://user-images.githubusercontent.com/58783823/71183523-250ce280-229e-11ea-860f-36d9e0f9c37c.png">

**Comment by SathyaJayabal** [comment]
@bug-hunt-helper help

**Comment by SathyaJayabal** [comment]
@bug-hunt-helper help

**Comment by SathyaJayabal** [comment]
@bug-hunt-helper help
