### ISSUE TITLE
New Nav: Some pages have incorrect navigation selection indicator

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#43]
1. Go to https://test-community-app.topcoder-dev.com/challenges and Login as dan_developer or any valid user
2. Click on Tracks --> Data Science --> Models and Algos
3. Check the New nav

Actual:
Selection indicator is on the "Community"

Expected:
It should be on the "Tracks"

![image](https://user-images.githubusercontent.com/5114190/60513596-4d575380-9cf5-11e9-8364-39b1d7a76c8b.png)

**Comment by SathyaJayabal** [comment]
verified
![Uploading Screenshot 2019-12-16 at 8.11.41 PM.png…]()

**Comment by SathyaJayabal** [comment]
<img width="1398" alt="Screenshot 2019-12-17 at 3 44 32 PM" src="https://user-images.githubusercontent.com/58783823/70986620-41651f80-20e4-11ea-84a9-5446808ab775.png">

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1440" alt="Screenshot 2019-12-19 at 8 14 25 PM" src="https://user-images.githubusercontent.com/58783823/71182506-3523c280-229c-11ea-9068-ebeb80d8d041.png">
