### ISSUE TITLE
$20 | Default profile image is not loaded if there is no profile pic set for the user

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#47]
Check the new navbar after logging in with a user that has no image set up in the profile

Actual:
Default image is not loaded.

![image](https://user-images.githubusercontent.com/5114190/68402772-dbf74800-01a1-11ea-9284-31117d930f52.png)

**Comment by luizrrodrigues** [comment]
Fixed PR #48

**Comment by nithyaasworld** [comment]
Verified @luizrrodrigues 

@Oanh-and-only-Oanh Currently it displays the following image as default pic, but it doesn't look good :) are we okay with this?

Or can we go with default image like seen [here ](https://www.google.com/url?sa=i&url=https%3A%2F%2Ficon-library.net%2Ficon%2Fdefault-profile-icon-24.html&psig=AOvVaw2vb2wSYvQ_oxr7vnRf1jy8&ust=1574924909876000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOCBj93qieYCFQAAAAAdAAAAABAD) 

![image](https://user-images.githubusercontent.com/5114190/69701537-2752a580-1113-11ea-9b42-3ea3eb495a8a.png)

**Comment by luizrrodrigues** [comment]
Update: Default icon need same like old nav.

**Comment by LieutenantRoger** [comment]
MR: https://github.com/topcoder-platform/navigation-component/pull/118 

I added a profile svg file which is found from the community app repo.

**Comment by LieutenantRoger** [comment]
![image](https://user-images.githubusercontent.com/2875203/72418404-bac06280-37b5-11ea-8ebd-323130b047da.png)

**Comment by SathyaJayabal** [comment]
For some users the default image is displayed correctly
<img width="488" alt="Screenshot 2020-01-21 at 12 10 35 PM" src="https://user-images.githubusercontent.com/58783823/72781353-12901b00-3c47-11ea-820e-515c91ec8295.png">

For some users the default image is a bit compressed
<img width="517" alt="Screenshot 2020-01-21 at 12 12 09 PM" src="https://user-images.githubusercontent.com/58783823/72781488-6569d280-3c47-11ea-97fa-c8abb5d0b16d.png">

**Comment by macs054** [comment]
Verified on Beta

![image](https://user-images.githubusercontent.com/1199534/75411819-8666c700-595b-11ea-8b87-2d8be171f5fb.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="423" alt="Screenshot 2020-02-28 at 8 41 28 AM" src="https://user-images.githubusercontent.com/58783823/75507126-2a0cb180-5a06-11ea-9a5d-f620f7bbd3b3.png">
