### ISSUE TITLE
'Switch to Business' link is not available for Customer user

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#49]
1. Go to connect.topcoder.com and create a customer user ( I created this user: PleaseIgnore pw: Jackle123$ )
2. Then go to community challenge listing page
3. Check the User dropdown menu

Actual:
Though this user is a customer user, User dropdown doesn't have 'Switch to Business' Option.

![image](https://user-images.githubusercontent.com/5114190/68407589-d43ba180-01a9-11ea-9f88-001bdd6f06a2.png)

**Comment by luizrrodrigues** [comment]
@nithyaasworld Moving discuss in Slack with @Oanh-and-only-Oanh here.

We going to follow this way:

- Show switch button to all members
- If have Copilot, admin, etc role . Go to Connect
- If not go to www.topcoder.com


![](https://user-images.githubusercontent.com/7029641/68440010-7b1f3e00-01a8-11ea-8f84-7b9742ff723b.png)

![](https://user-images.githubusercontent.com/7029641/68440010-7b1f3e00-01a8-11ea-8f84-7b9742ff723b.png)

![](https://user-images.githubusercontent.com/7029641/68440010-7b1f3e00-01a8-11ea-8f84-7b9742ff723b.png)

![](https://user-images.githubusercontent.com/7029641/68440010-7b1f3e00-01a8-11ea-8f84-7b9742ff723b.png)

**Comment by luizrrodrigues** [comment]
Fixed PR #50

**Comment by nithyaasworld** [comment]
@luizrrodrigues 
The following 2 issues are observed for Copilot user:

![image](https://user-images.githubusercontent.com/5114190/69702072-68978500-1114-11ea-9a17-610602fd3a0d.png)

**Comment by nithyaasworld** [comment]
@luizrrodrigues Please ignore the above. They seem to be working. I will recheck and update.

**Comment by nithyaasworld** [comment]
@luizrrodrigues @Oanh-and-only-Oanh 

Customer users have the user role as 'Topcoder User'. Example: This user 'tco19customer01' has user role as 'Topcoder User', though he is a customer user.

In this case, clicking on 'Switch to Business', just takes the user to www.topcoder.com

How should we handle this?

**Comment by nithyaasworld** [comment]
Also @luizrrodrigues When Lakshmi checked her account in Production (her account is admin account), it got redirected to www.topcoder.com and not to connect.topcoder.com

**Comment by nithyaasworld** [comment]
Thanks Lakshmi for helping in testing for the below roles. 

@luizrrodrigues  Please find below the issues with other roles apart from the Customer-User:

**Copilot Manager** - redirects to topcoder.com when 'Switch to Business' link is clicked
**Connect Account Manager** - redirects to topcoder.com when 'Switch to Business' link is clicked

**Comment by luizrrodrigues** [comment]
@nithyaasworld Thanks for check.

@Oanh-and-only-Oanh Just want to confirm, we don't will follow what have discussed in Slack early: https://github.com/topcoder-platform/navigation-component/issues/49#issuecomment-557217835

So will just redirect to Connect if user was a Copilot, all other user go to www.topcoder.com?

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, correct. thanks for checking.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Okay, cool. I'll update that.

**Comment by luizrrodrigues** [comment]
I'll create 2 new tickets to cover **Copilot Manager** and **Connect Account Manager**

**Comment by luizrrodrigues** [comment]
@nithyaasworld Can you please share account used to test:
Copilot Manager
Connect Account Manager

**Comment by lakshmiathreya** [comment]
<img width="690" alt="Screenshot 2019-11-29 at 10 17 10 AM" src="https://user-images.githubusercontent.com/51733042/70113130-01328580-167e-11ea-9a9c-784c8d4e2ce4.png">
fyi @nithyaasworld @luizrrodrigues

**Comment by nithyaasworld** [comment]
Thanks @lakshmiathreya 

Here is another set @luizrrodrigues 

topcoderconnect+Copilot@gmail.com
topcoderconnect+Customer@gmail.com
topcoderconnect+CopilotManager@gmail.com
topcoderconnect+AccountManager@gmail.com
topcoderconnect+Manager@gmail.com
topcoderconnect+Admin@gmail.com
topcoderconnect+Observer@gmail.com

Password for all the above users: appirio123

**Comment by lakshmiathreya** [comment]
@luizrrodrigues - for this Issue, my set was used. However, going forward we recommend using the topcoderconnect+* generic set since you get access to the topcoderconnect@gmail.com inbox as well - will help complete notification testing independently.

**Comment by lakshmiathreya** [comment]
cc @picachui

**Comment by SathyaJayabal** [comment]
@luizrrodrigues 
Connect Copilot Manager - redirects to topcoder.com when 'Switch to Business' link is clicked
Connect Account Manager - redirects to topcoder.com when 'Switch to Business' link is clicked

**Comment by luizrrodrigues** [comment]
@SathyaJayabal The main issue reported here was fixed.

We'll cover the Copilot Manager and Account Manager her:
https://github.com/topcoder-platform/navigation-component/issues/63

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , Ok, closing this

**Comment by SathyaJayabal** [comment]
Verified in Production
<img width="1437" alt="Screenshot 2019-12-19 at 8 12 19 PM" src="https://user-images.githubusercontent.com/58783823/71182332-ec6c0980-229b-11ea-97f7-21ac87ba0a19.png">
