### ISSUE TITLE
New Navi: Accessibility issue on the User dropdown

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#51]
1. Access the New Navigation bar present in the challenge listing page
2. Open the user dropdown menu and run the WCAG Color Contrast Checker Chrome extension

Actual:
The following 1 accessibility issue is noted.

![image](https://user-images.githubusercontent.com/5114190/68324731-fc65ca80-00ed-11ea-90da-31f0840a3939.png)

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld 
Fixed PR #52

**Comment by nithyaasworld** [comment]
Verified in beta. 

No Accessibility issue is seen on User dropdown menu.

![image](https://user-images.githubusercontent.com/5114190/69720639-1ae14380-1139-11ea-8ff0-57d17225b92d.png)

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1402" alt="Screenshot 2019-12-20 at 11 28 28 AM" src="https://user-images.githubusercontent.com/58783823/71233557-f9c8d880-231b-11ea-9dc9-671de3e583ad.png">
