### ISSUE TITLE
Profile Menu  Does Not Display The Correct Items in Mobile View

### ISSUE THREAD

**Issue by VanitaW** [topcoder-platform/navigation-component#54]
**Describe the bug**
The profile menu is not display the item defined in the requirements.

**To Reproduce**
1. Open safari browser on iOS mobile device.
2.  Go to https://test-community-app.topcoder-dev.com/challenges .
2. Click on 'Login'
3. Sign in using username: dan_developer password: dantopcoder123 . If you are redirected to  to the Topcoder live site, go to https://test-community-app.topcoder-dev.com/challenges
4.  Click on the profile picture in the upper right hand corner.
5.  Observe the items listed in the menu.

**Expected behavior**
The menu items should match the menu items listed in the requirements.

**Screenshots**

![MobileRequirements](https://user-images.githubusercontent.com/12702517/59133095-8ee62000-893c-11e9-8922-735e16214c2c.png)

![iOSProfileMenuItems](https://user-images.githubusercontent.com/12702517/59133097-90afe380-893c-11e9-975e-aa5e2b01be34.png)

**Smartphone:**
 - Device: iPhone SE
- OS: iOS12.2
 - Browser: Safari
 - Version:  12

**Comment by luizrrodrigues** [comment]
This one was fixed, waiting for approve of PR #55

**Comment by luizrrodrigues** [comment]
@nithyaasworld This one was fixed and ready to QA

**Comment by SathyaJayabal** [comment]
Verified
![IMG_5543](https://user-images.githubusercontent.com/58783823/70912808-c0058280-203a-11ea-8076-73050580d4ca.jpg)

**Comment by SathyaJayabal** [comment]
Verified

**Comment by SathyaJayabal** [comment]
verified in production.
![29064](https://user-images.githubusercontent.com/58783823/71186768-c8142b00-22a3-11ea-9bae-c52f7776149b.jpg)
