### ISSUE TITLE
New Nav: Let's collapse second level menu under the following tabs: competitive programming, data science, Statistics

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/navigation-component#56]
let's collapse second level menu under the following tabs: competitive programming, data science, Statistics

**Comment by SathyaJayabal** [comment]
Verified.
<img width="1398" alt="56 logged out verification 1" src="https://user-images.githubusercontent.com/58783823/70772953-07baae80-1d9c-11ea-823c-18b71e6c9e2b.png">
<img width="1397" alt="56 verification" src="https://user-images.githubusercontent.com/58783823/70772955-08534500-1d9c-11ea-8229-363fb1012846.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal  If all good, please add QA Pass tag. Thanks.

**Comment by SathyaJayabal** [comment]
I dont have access here (topcoder-platform/navigation-component) to edit the labels. @sushilshinde, can you please add me to this repository please ? 

@nithyaasworld please add the QA Pass tag, as this has been verified.

**Comment by SathyaJayabal** [comment]
Verified

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1437" alt="Screenshot 2019-12-19 at 7 48 09 PM" src="https://user-images.githubusercontent.com/58783823/71180630-99448780-2298-11ea-9239-41c8ed372ac2.png">
![Uploading Screenshot 2019-12-19 at 7.48.40 PM.png…]()
