### ISSUE TITLE
Explore - > TCO : Wrong sub menu item is highlighted

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#58]
**Describe the bug**
Explore - > TCO : Wrong sub menu item is highlighted

**To Reproduce**
1. Click on Explore -> TCO
2. TCO page opens in production
3. Manually edit the URL to access the tco page on beta env 
https://beta-community-app.topcoder.com/community/member-programs/topcoder-open/

**Expected behavior**
1. Page should open in beta env
2. TCO sub menu must be highlighted instead of Programs

**Screenshots**
<img width="1398" alt="TCO bug " src="https://user-images.githubusercontent.com/58783823/70791673-883dd700-1dbd-11ea-971a-878363cbb587.png">

**Comment by luizrrodrigues** [comment]
This one was fixed PR https://github.com/topcoder-platform/navigation-component/pull/59

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld @sachin-maheshwari 
This one was fixed/deployed and ready to test.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, the submenu TCO has a 404 error
![image](https://user-images.githubusercontent.com/47536078/70853208-ce4b7700-1e5f-11ea-8c5a-8657d0db74e1.png)

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh hum. looks like was changed the TCO link:

https://www.topcoder.com/tco 

not redirect to 

https://www.topcoder.com/community/member-programs/topcoder-open/

This will be the new link or keep using /tco?

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, please use this link https://www.topcoder.com/community/member-programs/topcoder-open/

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , Still has the issue
<img width="1401" alt="Screenshot 2019-12-15 at 10 40 06 AM" src="https://user-images.githubusercontent.com/58783823/70858391-63657300-1f27-11ea-9a2f-fed3171f4b5c.png">

**Comment by SathyaJayabal** [comment]
verified in beta
<img width="1391" alt="Screenshot 2019-12-17 at 10 58 11 AM" src="https://user-images.githubusercontent.com/58783823/70967459-4f9f4580-20bc-11ea-881b-4b0bee427bd3.png">

**Comment by SathyaJayabal** [comment]
Verified in production
![Uploading Screenshot 2019-12-19 at 7.40.58 PM.png…]()
