### ISSUE TITLE
$40 | No switch to business option on mobile web

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/navigation-component#6]
**Reproduction steps:**

1. Open the test URL and log in
2. Click on the user drop down menu at the top right corner
3. Observe

**Expected result:** 
There is an option to switch to business in the user menu on mobile web, like there is on desktop

**Actual result:** 
There is no switch to business option on mobile web

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome

**Screenshot:**

![screenshot2](https://user-images.githubusercontent.com/45698232/59125063-22582a80-8916-11e9-9b78-38fb5f728999.jpg)

**Comment by luizrrodrigues** [comment]
@nahidshahin Thanks.

**Comment by SathyaJayabal** [comment]
@bug-hunt-helper help
