### ISSUE TITLE
Blog page goes to 404 in beta env

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#61]
**Describe the bug**
Blog page goes to 404 in beta env

**To Reproduce**
1. Click on Explore -> Blog

**Expected behavior**
https://beta-community-app.topcoder.com/blog should display the blog
**Screenshots**
<img width="1405" alt="Screenshot 2019-12-16 at 3 44 51 PM" src="https://user-images.githubusercontent.com/58783823/70898646-0e0a8e00-201b-11ea-876a-52cddec7c69b.png">

**Comment by SathyaJayabal** [comment]
cc @@lakshmiathreya

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Thanks for check.

Blog not available in Beta server, in Prod will redirect to:
https://www.topcoder.com/blog
