### ISSUE TITLE
$15 | 'Switch to Business' link is not redirect to Connect to Connect  Copilot Manager and Connect  Account Manager

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#63]
Connect Copilot Manager - redirects to topcoder.com when 'Switch to Business' link is clicked
Connect Account Manager - redirects to topcoder.com when 'Switch to Business' link is clicked

**Comment by rashmi73** [comment]
@luizrrodrigues PR https://github.com/topcoder-platform/navigation-component/pull/79

**Comment by SathyaJayabal** [comment]
Verified in test env.

**Comment by SathyaJayabal** [comment]
Verified for lakshmiaCopMgr and lakshmiaAcMgr in Beta

**Comment by SathyaJayabal** [comment]
Verified for lakshmiaCopMgr and lakshmiaAcMgr in prod
