### ISSUE TITLE
$30 | Selection indicator moves away when the window is resized

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#67]
Selection indicator moves away when the window is resized
<img width="1151" alt="Screenshot 2019-12-19 at 7 58 57 PM" src="https://user-images.githubusercontent.com/58783823/71181439-29cf9780-229a-11ea-96ce-ff76c009b81a.png">

cc @nithyaasworld

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @sushilshinde @Oanh-and-only-Oanh need a new milestone to track pls!

**Comment by yoution** [comment]
please assign to me

**Comment by yoution** [comment]
@luizrrodrigues   can not reproduce, may there are the same problem, https://github.com/topcoder-platform/community-app/issues/2407.

**Comment by luizrrodrigues** [comment]
@yoution Looks like related, let me check.

**Comment by luizrrodrigues** [comment]
@yoution Please feel free to work in another issue for now if wanted.

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/navigation-component/issues/95

Issue tracked here
