### ISSUE TITLE
$15 | Error on track pages

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/navigation-component#70]
When hitting any of the track pages error is triggered in console. Try any of:
- https://www.topcoder.com/community/qa
- https://www.topcoder.com/community/development
- https://www.topcoder.com/community/design
- https://www.topcoder.com/community/data-science
- https://www.topcoder.com/community/competitive-programming

```
raven.js:390 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at main-1576755706850.js:108
    at main-1576755706850.js:108
    at main-1576755706850.js:108
    at main-1576755706850.js:108
    at d (raven.js:386)
```

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @nithyaasworld pls update label milestone and assignee

**Comment by LieutenantRoger** [comment]
MR: https://github.com/topcoder-platform/navigation-component/pull/116

**Comment by SathyaJayabal** [comment]
@luizrrodrigues the above error is not thrown. But for the below page

**Comment by LieutenantRoger** [comment]
I think the issue in `QA Phase` should fire a new bug, right ?  @luizrrodrigues @SathyaJayabal

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Yes, sorry I miss to comment here.

@SathyaJayabal This error not related with the original issue in ticket, this is related with server response error. 

I think we need to QA Pass this one.

cc @nithyaasworld

**Comment by macs054** [comment]
Verified in Beta
[issue_70_beta.zip](https://github.com/topcoder-platform/navigation-component/files/4259544/issue_70_beta.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
