### ISSUE TITLE
Adding Member Search to the New Nav

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#73]
1. Adding member search to the new nav

**Comment by SathyaJayabal** [comment]
@luizrrodrigues, On testing the member search on beta:
Search functionality works fine. There were just a couple of minor issues.

1. Search results page is displayed in prod. The search results page does not have the new nav. 
<img width="1431" alt="Screenshot 2020-01-07 at 7 33 00 PM" src="https://user-images.githubusercontent.com/58783823/71900851-a4e2ea00-3184-11ea-99b9-bb9c1717d379.png">
2. The search icon seems too much in the right corner. You can see the old search icon had more space to the right.
<img width="1435" alt="Screenshot 2020-01-07 at 7 40 05 PM" src="https://user-images.githubusercontent.com/58783823/71901310-b082e080-3185-11ea-8f5f-1a966be1e583.png">
<img width="1430" alt="Screenshot 2020-01-07 at 7 40 39 PM" src="https://user-images.githubusercontent.com/58783823/71901311-b082e080-3185-11ea-8271-c8c8490160b2.png">
3.The current page selection indicator looks a bit odd when search panel is displayed.
<img width="1434" alt="Screenshot 2020-01-07 at 7 41 45 PM" src="https://user-images.githubusercontent.com/58783823/71901418-ea53e700-3185-11ea-88e9-f3f287a0903c.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Let me know if test is done, so we request to fix these minor issues.

cc @nithyaasworld

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , let me do a quick smoke test on beta and will let you know.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues, i dont see any other issues other than the ones mentioned above

**Comment by nithyaasworld** [comment]
@luizrrodrigues Just like to add that we coulnd't verify the fix because of the issue stated in No:1 point added by Sathya here https://github.com/topcoder-platform/navigation-component/issues/73#issuecomment-571603621

Also if we change the production URL to beta URL, we get this error. Can you check once please?
![image](https://user-images.githubusercontent.com/5114190/71953360-fa140f80-3207-11ea-9f46-62f6ba931718.png)

cc: @SathyaJayabal

**Comment by luizrrodrigues** [comment]
@nithyaasworld 
1. Is like related here: https://github.com/topcoder-platform/community-app/issues/2670
Search results looks like a different app.

@sushilshinde can you confirm that?

**Comment by luizrrodrigues** [comment]
Note: 
1. https://github.com/appirio-tech/topcoder-app/blob/dev/app/layout/header/header.jade

**Comment by luizrrodrigues** [comment]
2. and 3. was fixed and deployed in Beta/Test servers.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues, 2 and 3 looks good
<img width="1400" alt="Screenshot 2020-01-10 at 5 08 02 PM" src="https://user-images.githubusercontent.com/58783823/72150582-d26da480-33cb-11ea-8cf3-9fe8e23a43a3.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , @sushilshinde 

What do you think of the background of the search box in the mobile view?  Should it be dark? Or is this the expected design ?

<img width="558" alt="Screenshot 2020-01-10 at 5 37 52 PM" src="https://user-images.githubusercontent.com/58783823/72152133-211d3d80-33d0-11ea-85ac-35a6aec9b66e.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , do we have a design document to refer to?

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I think we'll follow like desktop version colors.

You'll open a new issue followup this one?

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , yes I have.
https://github.com/topcoder-platform/navigation-component/issues/100
