### ISSUE TITLE
Navi CSS over-riding contentful CSS pages

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/navigation-component#74]
**Describe the bug**
scroll down on any page built on /community
the nav CSS is over riding the CSS for it'

https://www.topcoder.com/community/learn

**Screenshots**
![image](https://user-images.githubusercontent.com/47536078/71196298-a20b6e00-2244-11ea-9b1c-8de2905a1106.png)

**Comment by SathyaJayabal** [comment]
Verified in Production
<img width="1427" alt="Screenshot 2020-01-03 at 5 32 58 PM" src="https://user-images.githubusercontent.com/58783823/71722526-223df000-2e4f-11ea-964c-075da581f33d.png">
