### ISSUE TITLE
Add the Search feature from existing nav

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/navigation-component#77]
- We need just add like existing site, next to login/account button and show search input when hover the search icon.
- Please update search icon to white color (like menu text)
- All feature from existing search need be keep working

**Comment by SathyaJayabal** [comment]
@luizrrodrigues we already have an issue for this 
https://github.com/topcoder-platform/navigation-component/issues/73

**Comment by luizrrodrigues** [comment]
@SathyaJayabal no sure how not found this when search.

Thanks.

**Comment by luizrrodrigues** [comment]
Duplicate of #73
