### ISSUE TITLE
$50 | More option is not closing when user tap on other menus

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#9]
https://www.screencast.com/t/0Pygiruagy

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work > More
4. Tap on the Track or Compete menu

**Actual:** More option is not closing when user tap on other menus

**Expected:** More menu options should close when the user tries to tap on another menu

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@nahidshahin Please check feedback in PR #7

**Comment by nahidshahin** [comment]
@luizrrodrigues here is the 2nd PR on community-app https://github.com/topcoder-platform/community-app/pull/2624

**Comment by nahidshahin** [comment]
@luizrrodrigues as I told, it's a but difficult problem. Because two dropdown is part of two different component and it's parent component is in community-app project. So I need two PRs to fix this problem. Please take update from both PR then test again. Thanks

**Comment by nahidshahin** [comment]
@luizrrodrigues can you please increase the price a bit as it is a bit complex?

**Comment by luizrrodrigues** [comment]
@nahidshahin $50 looks good? (I need request to approve prize increase)
