### ISSUE TITLE
$15 | Arrow is not focused below the Work menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/navigation-component#97]
![image](https://user-images.githubusercontent.com/42398485/59126209-1c6c4480-892a-11e9-93b1-48495faa0a85.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click Menu > Work

**Actual:** Arrow is not focused below the Work menu

**Expected:** Arrow should display below the work menu

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Microsoft Edge 44.17763.1.0

**Comment by macs054** [comment]
Verified in Beta
![image](https://user-images.githubusercontent.com/1199534/75414721-7c959180-5964-11ea-822c-386943f47bc4.png)

**Comment by SathyaJayabal** [comment]
@macs054 , please verify and close this in production

**Comment by macs054** [comment]
Verified in Prod
![image](https://user-images.githubusercontent.com/1199534/75509112-61d52280-5a21-11ea-89d2-57e6b9893226.png)
